name: Deploy Airflow + Spark Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Authenticate to GCP
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_SALES_KEY }}'

    - name: Setup gcloud
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: kishan-learning-project-1

    # Upload PySpark jobs
    - name: Upload Spark Jobs to GCS
      run: |
        gsutil cp pyspark_jobs/*.py gs://airflow-pysaprk-dags/pyspark_jobs/

    # Upload DAGs
    - name: Upload Airflow DAGs
      run: |
        gsutil cp dags/*.py gs://us-central1-airflow-demo1-f877b8d6-bucket/dags/